package com.csse3200.game.services.audio;

public enum MusicId {
  DEFAULT_BGM, // TODO: remove
  MENU_HEARTHLIGHT,
  MENU_STORYBOOK,
  MENU_HEROES_GATE,
  MAP_WANDERER,
  MAP_FOG,
  MAP_CROSSROADS,
  BATTLE_CLASH,
  BATTLE_IRONCLAD,
  BATTLE_SKIRMISH,
  LIBRARY_ARCHIVE,
  LIBRARY_SPECIMENS,
  LIBRARY_STUDY,
  ELITE_BATTLE,
  BOSS_BATTLE,
  SHOP
}
